apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fastapi-app.fullname" . }}-config
  labels:
    {{- include "fastapi-app.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.env }}
  {{- if not (has $key (list "DATABASE_PASSWORD" "JWT_SECRET_KEY")) }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
