# ==============================================================================
# DEV environment overrides
# ==============================================================================
replicaCount: 1

env:
  ENVIRONMENT: "dev"
  LOG_LEVEL: "DEBUG"
  RATE_LIMIT: "200/minute"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

pdb:
  enabled: true
  minAvailable: 1

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: "api.35.187.23.141.nip.io"
      paths:
        - path: /
          pathType: Prefix

serviceAccount:
  annotations:
    iam.gke.io/gcp-service-account: "taskmanager-dev-app-sa@iac-dev-491314.iam.gserviceaccount.com"



